services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: thermostat-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
